:- multifile rule/3.
rule(op_us_bank_hack0, hasCapability(china,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(china,us_bank_hack)),[]).
rule(op_us_bank_hack2, governmentLinked(superhard,china),[]).
rule(op_us_bank_hack2, governmentLinked(dota,china),[]).
rule(op_us_bank_hack0, hasCapability(israel,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(israel,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(iran,us_bank_hack),[]).
rule(op_us_bank_hack1, hasMotive(iran,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(usa,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(usa,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(northkorea,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(northkorea,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(china,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(china,us_bank_hack)),[]).
rule(op_us_bank_hack2, governmentLinked(superhard,china),[]).
rule(op_us_bank_hack2, governmentLinked(dota,china),[]).
rule(op_us_bank_hack0, hasCapability(israel,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(israel,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(iran,us_bank_hack),[]).
rule(op_us_bank_hack1, hasMotive(iran,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(usa,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(usa,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(northkorea,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(northkorea,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(china,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(china,us_bank_hack)),[]).
rule(op_us_bank_hack2, governmentLinked(superhard,china),[]).
rule(op_us_bank_hack2, governmentLinked(dota,china),[]).
rule(op_us_bank_hack0, hasCapability(israel,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(israel,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(iran,us_bank_hack),[]).
rule(op_us_bank_hack1, hasMotive(iran,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(usa,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(usa,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(northkorea,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(northkorea,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(china,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(china,us_bank_hack)),[]).
rule(op_us_bank_hack2, governmentLinked(superhard,china),[]).
rule(op_us_bank_hack2, governmentLinked(dota,china),[]).
rule(op_us_bank_hack0, hasCapability(israel,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(israel,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(iran,us_bank_hack),[]).
rule(op_us_bank_hack1, hasMotive(iran,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(usa,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(usa,us_bank_hack)),[]).
rule(op_us_bank_hack0, hasCapability(northkorea,us_bank_hack),[]).
rule(op_us_bank_hack1, neg(hasMotive(northkorea,us_bank_hack)),[]).
rule(op_apt10, hasCapability(china,apt1),[]).
rule(op_apt11, neg(hasMotive(china,apt1)),[]).
rule(op_apt12, governmentLinked(superhard,china),[]).
rule(op_apt12, governmentLinked(dota,china),[]).
rule(op_apt10, hasCapability(israel,apt1),[]).
rule(op_apt11, neg(hasMotive(israel,apt1)),[]).
rule(op_apt10, hasCapability(iran,apt1),[]).
rule(op_apt11, neg(hasMotive(iran,apt1)),[]).
rule(op_apt10, hasCapability(usa,apt1),[]).
rule(op_apt11, neg(hasMotive(usa,apt1)),[]).
rule(op_apt10, hasCapability(northkorea,apt1),[]).
rule(op_apt11, neg(hasMotive(northkorea,apt1)),[]).
rule(op_gaussattack0, hasCapability(china,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(china,gaussattack)),[]).
rule(op_gaussattack2, governmentLinked(superhard,china),[]).
rule(op_gaussattack2, governmentLinked(dota,china),[]).
rule(op_gaussattack0, hasCapability(israel,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(israel,gaussattack)),[]).
rule(op_gaussattack0, hasCapability(iran,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(iran,gaussattack)),[]).
rule(op_gaussattack0, hasCapability(usa,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(usa,gaussattack)),[]).
rule(op_gaussattack0, hasCapability(northkorea,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(northkorea,gaussattack)),[]).
rule(op_gaussattack0, hasCapability(china,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(china,gaussattack)),[]).
rule(op_gaussattack2, governmentLinked(superhard,china),[]).
rule(op_gaussattack2, governmentLinked(dota,china),[]).
rule(op_gaussattack0, hasCapability(israel,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(israel,gaussattack)),[]).
rule(op_gaussattack0, hasCapability(iran,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(iran,gaussattack)),[]).
rule(op_gaussattack0, hasCapability(usa,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(usa,gaussattack)),[]).
rule(op_gaussattack0, hasCapability(northkorea,gaussattack),[]).
rule(op_gaussattack1, neg(hasMotive(northkorea,gaussattack)),[]).
rule(op_stuxnetattack0, hasCapability(china,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(china,stuxnetattack)),[]).
rule(op_stuxnetattack2, governmentLinked(superhard,china),[]).
rule(op_stuxnetattack2, governmentLinked(dota,china),[]).
rule(op_stuxnetattack0, hasCapability(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(iran,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(iran,stuxnetattack)),[]).
rule(op_stuxnetattack0, hasCapability(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(northkorea,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(northkorea,stuxnetattack)),[]).
rule(op_stuxnetattack0, hasCapability(china,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(china,stuxnetattack)),[]).
rule(op_stuxnetattack2, governmentLinked(superhard,china),[]).
rule(op_stuxnetattack2, governmentLinked(dota,china),[]).
rule(op_stuxnetattack0, hasCapability(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(iran,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(iran,stuxnetattack)),[]).
rule(op_stuxnetattack0, hasCapability(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(northkorea,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(northkorea,stuxnetattack)),[]).
rule(op_stuxnetattack0, hasCapability(china,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(china,stuxnetattack)),[]).
rule(op_stuxnetattack2, governmentLinked(superhard,china),[]).
rule(op_stuxnetattack2, governmentLinked(dota,china),[]).
rule(op_stuxnetattack0, hasCapability(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(iran,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(iran,stuxnetattack)),[]).
rule(op_stuxnetattack0, hasCapability(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(northkorea,stuxnetattack),[]).
rule(op_stuxnetattack1, neg(hasMotive(northkorea,stuxnetattack)),[]).
rule(op_sonyhack0, neg(hasCapability(_195,sonyhack)),[]).
rule(op_sonyhack1, hasMotive(northkorea,sonyhack),[]).
rule(op_wannacryattack0, neg(hasCapability(_195,wannacryattack)),[]).
rule(op_wannacryattack1, neg(hasMotive(_195,wannacryattack)),[]).
rule(op_wannacryattack2, governmentLinked(superhard,china),[]).
rule(op_wannacryattack2, governmentLinked(dota,china),[]).
