:- multifile rule/3.
rule(op_us_bank_hack0, hasCapability(china,us_bank_hack),[]).
rule(op_us_bank_hack2, governmentLinked(superhard,china),[]).
rule(op_us_bank_hack2, governmentLinked(dota,china),[]).
rule(op_us_bank_hack0, hasCapability(israel,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(iran,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(usa,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(northkorea,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(china,us_bank_hack),[]).
rule(op_us_bank_hack2, governmentLinked(superhard,china),[]).
rule(op_us_bank_hack2, governmentLinked(dota,china),[]).
rule(op_us_bank_hack0, hasCapability(israel,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(iran,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(usa,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(northkorea,us_bank_hack),[]).
rule(op_gaussattack0, hasCapability(china,gaussattack),[]).
rule(op_gaussattack2, governmentLinked(superhard,china),[]).
rule(op_gaussattack2, governmentLinked(dota,china),[]).
rule(op_gaussattack0, hasCapability(israel,gaussattack),[]).
rule(op_gaussattack0, hasCapability(iran,gaussattack),[]).
rule(op_gaussattack0, hasCapability(usa,gaussattack),[]).
rule(op_gaussattack0, hasCapability(northkorea,gaussattack),[]).
rule(op_stuxnetattack0, hasCapability(china,stuxnetattack),[]).
rule(op_stuxnetattack2, governmentLinked(superhard,china),[]).
rule(op_stuxnetattack2, governmentLinked(dota,china),[]).
rule(op_stuxnetattack0, hasCapability(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(iran,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(northkorea,stuxnetattack),[]).
rule(op_us_bank_hack0, hasCapability(china,us_bank_hack),[]).
rule(op_us_bank_hack2, governmentLinked(superhard,china),[]).
rule(op_us_bank_hack2, governmentLinked(dota,china),[]).
rule(op_us_bank_hack0, hasCapability(israel,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(iran,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(usa,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(northkorea,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(china,us_bank_hack),[]).
rule(op_us_bank_hack2, governmentLinked(superhard,china),[]).
rule(op_us_bank_hack2, governmentLinked(dota,china),[]).
rule(op_us_bank_hack0, hasCapability(israel,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(iran,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(usa,us_bank_hack),[]).
rule(op_us_bank_hack0, hasCapability(northkorea,us_bank_hack),[]).
rule(op_gaussattack0, hasCapability(china,gaussattack),[]).
rule(op_gaussattack2, governmentLinked(superhard,china),[]).
rule(op_gaussattack2, governmentLinked(dota,china),[]).
rule(op_gaussattack0, hasCapability(israel,gaussattack),[]).
rule(op_gaussattack0, hasCapability(iran,gaussattack),[]).
rule(op_gaussattack0, hasCapability(usa,gaussattack),[]).
rule(op_gaussattack0, hasCapability(northkorea,gaussattack),[]).
rule(op_stuxnetattack0, hasCapability(china,stuxnetattack),[]).
rule(op_stuxnetattack2, governmentLinked(superhard,china),[]).
rule(op_stuxnetattack2, governmentLinked(dota,china),[]).
rule(op_stuxnetattack0, hasCapability(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(iran,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(northkorea,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(china,stuxnetattack),[]).
rule(op_stuxnetattack2, governmentLinked(superhard,china),[]).
rule(op_stuxnetattack2, governmentLinked(dota,china),[]).
rule(op_stuxnetattack0, hasCapability(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(israel,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(iran,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack1, hasMotive(usa,stuxnetattack),[]).
rule(op_stuxnetattack0, hasCapability(northkorea,stuxnetattack),[]).
rule(op_apt10, hasCapability(china,apt1),[]).
rule(op_apt12, governmentLinked(superhard,china),[]).
rule(op_apt12, governmentLinked(dota,china),[]).
rule(op_apt10, hasCapability(israel,apt1),[]).
rule(op_apt10, hasCapability(iran,apt1),[]).
rule(op_apt10, hasCapability(usa,apt1),[]).
