us_bank_hack[58]hasCapability(china,us_bank_hack), derivation: 0
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]hasCapability(israel,us_bank_hack), derivation: 0
us_bank_hack[58]hasCapability(iran,us_bank_hack), derivation: 0
us_bank_hack[58]hasCapability(usa,us_bank_hack), derivation: 0
us_bank_hack[58]hasCapability(northkorea,us_bank_hack), derivation: 0
us_bank_hack[58]hasCapability(china,us_bank_hack), derivation: 0
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
us_bank_hack[58]governmentLinked(dota,china), derivation: 2
us_bank_hack[58]governmentLinked(superhard,china), derivation: 2
