:- multifile rule/3.
rule(t_us_bank_hack1, requireHighResource(us_bank_hack),[]).
rule(t_us_bank_hack1, requireHighResource(us_bank_hack),[]).
rule(t_us_bank_hack1, requireHighResource(us_bank_hack),[]).
rule(t_us_bank_hack1, requireHighResource(us_bank_hack),[]).
rule(t_apt11, requireHighResource(apt1),[]).
rule(t_gaussattack1, requireHighResource(gaussattack),[]).
rule(t_gaussattack1, requireHighResource(gaussattack),[]).
rule(t_stuxnetattack1, requireHighResource(stuxnetattack),[]).
rule(t_stuxnetattack1, requireHighResource(stuxnetattack),[]).
rule(t_stuxnetattack1, requireHighResource(stuxnetattack),[]).
rule(t__8513, neg(forBlackMarketUse(gauss)),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
rule(t_gaussattack5, similar(gauss,flame),[]).
